### ISSUE TITLE
General issues  after testing SORMAS 1.30.1 on Ghana server

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#1365]
Dear All, these a some points that I found after testing the new version. Some of them will need urgent fix if they are real bugs.

1. Web: default filters like"this year",  does not match the right time. Only CUSTOM PERIOD works. When I click on " This year", the CUSTOM PERIOD time does not update accordingly.  -> #1429 
2.  Mobile: when a user has both SO and CO roles, the default landing  page is "Contact listing". This should be case listing. -> #1371
3. Mobile: "Date received at LGA level" should be change to "Date received at District/ LGA level". Ghana do not know what LGA means -> #1372
4. Cases created by DSNOs does not appear in "case listing" and dashboard on the web app but are counted in statistics. Another mobile user (DSNO) can see the cases and changes made. These cases do not have an associated DSNO for which SORMAS was suppose to assign the DSNO who created the case as the associated DSNO by default. This is the same for cases created by DSNO localized in a HF -> see below, #1370
5. Cases created by localized dsno/dsno are not assigned to the respective dsno by defoault (see point 4) -> #1370
6. Case investigation  task for cases created by localized dsno is assigned to SS, CS, and  Event Officer, this should not be the case. This task should be assigned to the same dsno. -> #1370
7.  Both localized SO (LDSNO ) and SO receives a new case on their case listing when a new case is created in their  district. The LDSNO should not see cases that they did not create, only the dsno should see all cases in the district -> see below
8. Cases created on  web app appears on mobile app but  not vice versa -> see below
9. DOB should not  start at 1900, it cause users to scroll a lot and make mistakes. 1980 could be used as default -> #1371
10. Auto Epid number generation is not disease specific on HZI server, 1.30.1 but inclement by 1 when a new case is created and gives always the same epid number on Ghana server, 1.30.1. We also relisted that there are many cases on Nigerian server with the same epid number.  There is something to be refined in the epid number generation process and this issue is not the same on HZI and on Ghana servers. This is a suggested algorithm to generate Epid numbers: 
For each disease, Epid number = Country-region-district-year-n. n is the index vector of disease specific series vector from 1 to infinity. This means in a district, 2 cases of different diseases will have the same Epid number in the DB but not for the same disease. When a case is deleted or merged with another, it should not affect the series count increment fro that disease. Duplicate Epid number search should be based on diseases, region, district and year. System should not allow users to save duplicate epid numbers #1404 

Point 4 is  very important for tomorrow. @MartinWahnschaffeSymeda and @danieltomaba  Can you have a look at these points tomorrow morning?

11. We should display at least one test result of each sample on the right side of sample listing in   mobile app. Priority should be: positive, negative, pending. This will give the dsno an idea of sample sattus -> already there
12. Under vaccination status fro a measles case, "whichvaccine"  should be "Name of vaccine" in mobile app -> #1372
13. App jumps from one section to another, e.g. from sample to task, task to case when the edit button is clicked. This might be a bug. When edit button in clicked, app should stay on the same page and allow user to be able to edit the page they see -> #1358
14. Mobile: I wanted to edit a sample of a case, I went to the sample section of the case before clicking on the edit button. It did not allow me to add another sample. But is I choose edit the case before going to the sample section, it worked. Both options should work normally, this might be a bug. I could nto reproduce it on other tablets but the point 13 is always present. There is something fishy about the navigation with the drawer on the mobile  -> #1358
15. Replacing CSM with Meningitis at front end on mobile and web app -> #1372
16. Change Gender to sex at front end -> #1372
17. On dashboard: New event should be classified as: Possible becomes signal,  confirmed  becomes Event. The same classification in event section should be used on dashboard -> #1430
18. When bulk action is applied to delete all cases in a system, all associated data to the case should be deleted. Task are not deleted in the current version.
19.Web. When filling a page on the web having many fields, SORMAS refreshes each time a field is entered. This is annoying and disturbing to a user. The tool should refresh when the user click on save, or after about 3 min of staying on the web page without doing any thing. -> will change with other UI framework
20. Cases   created by SO, synchronization was successful but no task assigned to SO.   Responsible district diseases control officer is missing- This should always be   the SO of the district by default. If there are more than one SO in a district, priority should be the one creating the case. If the case is created by an   informant, SORMAS should assign the associated SO of the informant. If the case is created by another user higher in the hierarchy like Lab, SS,   etc the user should be allowed to choose the associated SO or the system should randomly assigned one of the SO in the district of the case. -> see below
21. In creating a case, sub district is not a required field, thus should not have * -> #1431
22.  When creating a case of VHF, SORMAS doen't ask exposure questions like travels, This should be added like for Lassa. VHF should be the combined exposure of all VHFs (Ebola, Lassa, etc). This is because at this point, we do not know the disease causing the illness - >#1432
23. For a VHF case, direct contact with "probable or confirmed case" should become "probable or suspected case" under epidemiological data -> skip
24. If an external lab result is tested positive fro Lassa after suspecting VHF, SORMAS should trigger the  user to create a Lassa case for the disease. -> working
25.  SORMAS should allow users on mobile app to be able to correct case data like disease etc -> #1433
26. SOs can change the district and region when editing a case, but they can do this when creating the case. They should be prevented from editing the region and district of the case that they are notifying -> needed for case transfer
27. Bug: Choosing editing key while in sample does  not create a new sample -> already fixed
28. Hospital  informants can classify a case as confirmed   without any lab test results. Is this right ? -> fixed
29. Serotype should not   show when test type is gram stain. -> works for me
30. Web app: when date sample is sent or received is checked, the current date if automatically prefilled,  we should not fill the date fields that follow but allow the user to choose the date. -> #1434
31. When the positive test result is created for a sample that differs from the initial notified pathogen, SORMAS does no trigger the user to create a new case fro the new disease. This only happens when the disease is the same as that for which the sample was collected. This might be problematic for the UVHF module since the lab results can lead to many diseases other than VHF. -> #1435
32. Mobile: Community  should be replaced by Sub-district at case creation step. This is already done for address of person -> was a caption issue
33. Web and app: Test result should have a category Others followed by free text added. This is because the results of gram stain (bed side test) can't have the option positive. -> skip until lab is refined
34. When entering the address of a person, Area type does not say if it is the district or the region. We should use "Area type of District" in Ghana and "Area type of LGA" for Nigeria -> #1436
35. Gram stain result should trigger classification by user but should have only Probable and suspected categories, Not confirmed -> skip
36. Creation date is missing on SS interface  of case menu. We should add it. -> creation date is technical. User can not edit it
37. Make  contacts listing and followup active for csm in Ghana -> see #1428 
38. date received at lga level shoiuld be hidden when logged in as informant #1437
39. "Not shipped" should not appear under  sample information fro internal samples #1438
40. A user with SO and CO roles localized to a health facility can change their state and district when notifying a case. This should be prevented -> solved
41. Create a web version for SO and Informant. OR make it possible fro them to export their line listing of cases that they have created through  from the mobile version -> #1439
42. SS, CS, and admins cannot assess visits of a contact. In addition, when you click on the contact icon while inside a case, the lost of all contacts are presented to you. Only the list of contacts associated to the case are to be presented. -> fixed

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou On point 4. and 9.:
WHat is the district of the DSNO who created the case? What is the user role and region (if so) of the user who was trying to see it in the web app?

On point 7:
I feel like we have to clearly point out what are the differences between a facility informant, a local DSNO and a DSNO are. If the local DSNO should only see his facility cases he might better be an informant in the first place?

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou
On point 1:
I tried, but cannot reproduce this. Can you provide an example and a screenshot? 

On points 4. and 9.:
WHat is the district of the DSNO who created the case? What is the user role and region (if so) of the user who was trying to see it in the web app?

On point 7:
I feel like we have to clearly point out what are the differences between a facility informant, a local DSNO and a DSNO are. If the local DSNO should only see his facility cases he might better be an informant in the first place?

**Comment by bernardsilenou** [comment]
Thanks Martin for the messages:
For point 1, I was wrong, it works. What derailed me was that after choosing "This year" the button that says " Apply custom filter says blue". We should deactivate it. We should not pre-filled the  custom filter date field. When the user insert a date field of interest, the top row that says "this year " should be deactivated. I hope you undersatnd me, if not just play with the fields and see
![image](https://user-images.githubusercontent.com/12996724/69137373-ef1ce880-0abc-11ea-9536-a107265e94bc.png)

The region is Upper west and district is Nadowli. There are two users, one having SO, CO right and another SO localised to a HF. The localised SO could create a sample but can not create a test result for the sample. I was the one trying to see the cases on the web app, I am admin. I could see on tablet cases created on web app but not vice versa.

On point 7:
I feel like we have to clearly point out what are the differences between a facility informant, a local DSNO and a DSNO are. If the local DSNO should only see his facility cases he might better be an informant in the first place? This is correct, I agree that the user should be an informant with posibility to collect sample, send to national lab, record beds side test results and some sample information, list contacts

**Comment by hzi-braunschweig** [comment]
> @bernardsilenou
> On point 1:
> I tried, but cannot reproduce this. Can you provide an example and a screenshot?
> 
> On points 4. and 9.:
> WHat is the district of the DSNO who created the case? What is the user role and region (if so) of the user who was trying to see it in the web app?
> 
> On point 7:
> I feel like we have to clearly point out what are the differences between a facility informant, a local DSNO and a DSNO are. If the local DSNO should only see his facility cases he might better be an informant in the first place?

@bernardsilenou  @MartinWahnschaffeSymeda I agree. We should not call the local DSNO a DSNO, he is an informant with some DSNO rights

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou Just talked to Daniel. Points 4 and 8 are solved by assigning a national user role to the user. An admin itself is currently not allowed to see cases in the system, because he is a technical user.

On the pathogen tests:
When you open a sample and switch to the edit view and then go to the pathogen test listing, you should see a plus button on the top right. This button will appear when your user does have the surveillance officer user role.

**Comment by bernardsilenou** [comment]
> @bernardsilenou Just talked to Daniel. Points 4 and 8 are solved by assigning a national user role to the user. An admin itself is currently not allowed to see cases in the system, because he is a technical user.
> 
> On the pathogen tests:
> When you open a sample and switch to the edit view and then go to the pathogen test listing, you should see a plus button on the top right. This button will appear when your user does have the surveillance officer user role.

This is fine now Martin. What is still missing is that a sample that was taken by a dsno and sent for external lab testing can also be edited and assign a lab result by the dsno. This should not be the case for external samples

**Comment by MartinWahnschaffeSymeda** [comment]
@bernardsilenou I have updated your post with links to resulting tickets on github
