### ISSUE TITLE
server setup error - 'PSQLException: ERROR: syntax error at or near "#"'

### ISSUE THREAD

**Issue by Soontao** [hzi-braunschweig/SORMAS-Project#1514]
Hello maintainers, 

When I try to setup (run the `server-update` script to deploy app) a SORMAS server, I meet an exception **'PSQLException: ERROR: syntax error at or near "#"'**, do you have any ideas about that ? 

![image](https://user-images.githubusercontent.com/10473459/74310668-ac5f6980-4da8-11ea-9c34-fb383228c189.png)

In addtion, when I execute the 'server-setup.sh' & 'server-update' script, there are many errors like 'permission deny'/'windows line break run', could you update the script for the new released version ? or give a tested running environment like (ubuntu 14,gcc7,run with root user blabla )

Thanks for your help.

**Comment by MateStrysewskeSym** [comment]
Hey!

Concerning the line break issue - this will be resolved with the next release. For now, you can use "dos2unix" to convert the line endings to unix style. You'll probably have to install the package and then just type in `dos2unix ./server-update.sh`, `dos2unix ./server-setup.sh` and `dos2unix ./server-update.conf`.

Apart from that, you definitely need to run all these scripts with root permissions.

The PSQLException is something I've not seen before. Just to clarify, you successfully ran the setup script and now try to deploy the latest version with the update script, right? When exactly does this exception happen (i.e. what's the last of the instructions printed to the console before it occurs)? Also, please navigate to the log file (by default /opt/domains/sormas/logs/server.log) and paste the whole stack trace here.

**Comment by Soontao** [comment]
Hello @MateStrysewskeSym 

Thanks for your quickly reply, please check the attachment to get the server log.

[server.log document](https://github.com/hzi-braunschweig/SORMAS-Project/files/4190597/server.log)

The running environment for this `server.log` is:

* Ubuntu 16
* PSQL 9.5 with extension

I think, if you never meet this problem before, it maybe caused by the `hibernate` version/or `other dependencies` version/or system environment..., I've tried PSQL with 9.5 and 10, and both version PSQL will throw this exception.

In fact, the "#" mark is totally not an SQL statement.


Thanks for your help. :)

**Comment by MateStrysewskeSym** [comment]
Thanks for sending the log file! It could take us some time to figure out the root of this problem. In the meantime, to get your server up and running, you could try to manually execute the SQL scripts from the [master branch](https://github.com/hzi-braunschweig/SORMAS-Project/tree/master/sormas-backend/src/main/resources/sql), e.g. by using pgAdmin. That should get rid of the deployment error.

If that doesn't solve it (or you need assistance in performing these steps), please get back to me!

**Comment by jenningsloy318** [comment]
I try to execute two sql, but the same error still exists. 

Can you show me when to execute these sqls ? I tried to execute it before/after  server-setup.sh, but no luck.

**Comment by MateStrysewskeSym** [comment]
They need to be executed after server-setup.sh. If you get the same error, does pgAdmin tell you the line that causes it?

**Comment by jenningsloy318** [comment]
many errors ,some of them are 
```
ERROR:  function versioning() does not exist
ERROR:  trigger "versioning_trigger" for table "userroles" does not exist                                                                                                                    
ERROR:  duplicate key value violates unique constraint "schema_version_pkey"                                                                                                                 │·················································
DETAIL:  Key (version_number)=(1) already exists.                                                                                                                                            │·················································
ERROR:  duplicate key value violates unique constraint "schema_version_pkey"                                                                                                                 │·················································
DETAIL:  Key (version_number)=(2) already exists.                                                                                                                                            │·················································

```

**Comment by MateStrysewskeSym** [comment]
It's possible that a part of the SQL script has already run. I'd suggest that you have a look into the server-setup.sh and server-update.sh scripts and set up the databases manually. I'll have a look into these issues and try to fix them for the next release (which is due next week), so alterantively you could try to wait until then.

Also, make sure that you remove the SORMAS server completely (including the databases), run the server-setup script again and manually update the databases BEFORE running the server-update script. That should at least get rid of the duplicate key errors.

**Comment by jenningsloy318** [comment]
yes, I tried several times. each time I deleted all files under /opt, and empty the database and reinitialize the db.

and the sqls in server-setup.sh only contains following lines
```
CREATE USER $DB_USER WITH PASSWORD '$DB_PW' CREATEDB;
CREATE DATABASE $DB_NAME WITH OWNER = '$DB_USER' ENCODING = 'UTF8';
CREATE DATABASE $DB_NAME_AUDIT WITH OWNER = '$DB_USER' ENCODING = 'UTF8';
\c $DB_NAME
CREATE OR REPLACE PROCEDURAL LANGUAGE plpgsql;
ALTER PROCEDURAL LANGUAGE plpgsql OWNER TO $DB_USER;
CREATE EXTENSION temporal_tables;
CREATE EXTENSION pg_trgm;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO $DB_USER;
\c $DB_NAME_AUDIT
CREATE EXTENSION IF NOT EXISTS plpgsql WITH SCHEMA pg_catalog;
COMMENT ON EXTENSION plpgsql IS 'PL/pgSQL procedural language';
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO $DB_USER;
CREATE TABLE schema_version (
  version_number integer NOT NULL,
  changedate timestamp without time zone NOT NULL DEFAULT now(),
  comment character varying(255),
    CONSTRAINT schema_version_pkey PRIMARY KEY (version_number)
    );
ALTER TABLE IF EXISTS schema_version OWNER TO $DB_USER;
````

and the sormas_schema.sql contains "#", so errors will also appear.
```
#-- If a DB update was performed, insert a new line with a comment to the table SCHEMA_VERSION.
-- Example: INSERT INTO schema_version (version_number, comment) VALUES (1, 'Init database');

-- #1
````

also there are   other errors, 
- 
```
aused by: javax.naming.NamingException: Lookup failed for 'java:global/sormas-ear/sormas-backend/ConfigFacade' in SerialContext[myEnv={java.naming.factory.initial=com.sun.enterprise.naming.impl.SerialInitContextFactory, java.naming.factor
y.state=com.sun.corba.ee.impl.presentation.rmi.JNDIStateFactoryImpl, java.naming.factory.url.pkgs=com.sun.enterprise.naming} [Root exception is javax.naming.NameNotFoundException: ConfigFacade not found]
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:496)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:442)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at javax.naming.InitialContext.lookup(InitialContext.java:417)
        at de.symeda.sormas.api.FacadeProvider.lookupEjbRemote(FacadeProvider.java:249)
        ... 68 more
Caused by: javax.naming.NameNotFoundException: ConfigFacade not found
        at com.sun.enterprise.naming.impl.TransientContext.doLookup(TransientContext.java:237)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:204)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
        at com.sun.enterprise.naming.impl.TransientContext.lookup(TransientContext.java:208)
        at com.sun.enterprise.naming.impl.SerialContextProviderImpl.lookup(SerialContextProviderImpl.java:70)
        at com.sun.enterprise.naming.impl.LocalSerialContextProviderImpl.lookup(LocalSerialContextProviderImpl.java:114)
        at com.sun.enterprise.naming.impl.SerialContext.lookup(SerialContext.java:483)
        ... 72 more
```

**Comment by MateStrysewskeSym** [comment]
I've just realised that my colleague apparently already encountered and fixed this issue, which is why I couldn't find that '#' sign on my development system. That means this bug will definitely be resolved with the next release.

All the other exceptions from the log files likely only occur as a result of the initial problem.

Until then, please make sure that you completely remove the database (don't only empty it - remove it from your system), run the server-setup.sh and then manually execute the contents of the sql schemas. Make sure to remove the '#' from the start of the file. Run the server-update.sh afterwards.

**Comment by jenningsloy318** [comment]
As this sql is embeded in the jar files, so this error will not fixed until new version is released.

**Comment by MateStrysewskeSym** [comment]
@jenningsloy318 Exactly, but like I said, you should be able to execute it manually before using the server-update script.

**Comment by jenningsloy318** [comment]
Hi @MateStrysewskeSym  I used follow steps, but no luck
1. delete all files under /opt
2. delete db 
3. reinitial new db 
4. execute server-setup.sh
5. excute two sql  files (remove the # lines)
6. excute server-update.sh


but the same error still exists, as the server starts will load all jar files, which sql is embeded in one of them, so this sql still be checked at this time, so the error will not fix.

**Comment by MateStrysewskeSym** [comment]
@jenningsloy318 Alright. I hoped the malformed SQL wouldn't be a problem if the script doesn't try to execute it, but apparently merely reading it is a problem.

In that case, I'm afraid you'll have to wait until next week, likely Wednesday, for the new version to be released. I'll make sure that this bug is fixed and the server setup routine is working as intended by then. I'm really sorry for the inconvenience.

**Comment by MateStrysewskeSym** [comment]
@Soontao @jenningsloy318 Considering that this whole matter is probably pretty time-sensitive for you, I've just released a hotfix that removes the misplaced "#" from the SQL file. You should be able to set up a server with the hotfix version.

**Comment by Soontao** [comment]
@MateStrysewskeSym 

Thank you very much for your reply.
In fact, after manually edit the SQL file, I have successfully setup the server yesterday. Everything works fine.  

Have a nice day ! :)

**Comment by MateStrysewskeSym** [comment]
@Soontao That's great to hear! I'll close this issue then.
