### ISSUE TITLE
We need to have OTHER HEALTH FACILITY using  BULK EDIT 

### ISSUE THREAD

**Issue by Mabayoje** [hzi-braunschweig/SORMAS-Project#2616]
We have cases created by POE informant for returnees but they were all refereed to Health Facility in another district for checkups and samples collection. Using bulk edit to CHANGE  the health facility in another district

No other health facility from the the Change health facility BULK EDIT

**Comment by MartinWahnschaffeSymeda** [comment]
@Mabayoje This should be working now

![grafik](https://user-images.githubusercontent.com/23217632/94112966-79a14780-fe46-11ea-84c9-94fa0d452c1e.png)

**Comment by Mabayoje** [comment]
![Other HF](https://user-images.githubusercontent.com/54799249/94142551-600ff800-fe66-11ea-9a9b-83c49531eee3.PNG)
The Other Facility is still missing
