### ISSUE TITLE
Source case name does not show before save in exposures list

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3624]
### Bug Description
When selecting a previously entered source case contact in the exposure form, the selected source case does not get displayed in the exposure list.
### Steps to Reproduce
1. go to the epi data tab of a case.
2. create a contact to a source case.
3. create a new exposure and select the previously entered source case.
4. check the exposure detail list for the name if the source case.

### Expected Behavior
The exposure list should display the name of the source case when selected in the exposure creation form.
### Screenshots
<img width="694" alt="epiDataSourceName" src="https://user-images.githubusercontent.com/70317594/100528702-cd7e3300-31df-11eb-8488-a0a2e03f9a6f.PNG">
<img width="512" alt="ExposureSourceContact" src="https://user-images.githubusercontent.com/70317594/100528705-d242e700-31df-11eb-99d5-5dd501433670.PNG">

### System Details
* Device:
* SORMAS version: 1.52
* Android version/Browser: firefox
* Server URL: test1401.sormas-oegd.de
* User Role: admin, national user

**Comment by MateStrysewske** [comment]
FYI: The source case name will appear after you've hit "Save". I've fixed it anyway so that it now appears immediately after the exposure has been added to the list.

**Comment by raghupola-vg** [comment]
Name of Source case still doesn't appear in the list of exposures. Neither after adding the the exposure nor after clicking on save at the epi data tab. Issue reopened.
Tested on url: https://test1401.sormas-oegd.de/

**Comment by kwa20** [comment]
@raghupola-vg I think what you've selected is a contact that doesn't have a source case. That contact is listed on the right but says no source case. In the corresponding drop down menu in exposures, the name that is listed is the case itself (cf. case check mate on test1401).

**Comment by AndyBakcsy-she** [comment]
Closing issue as verified on local environment on version 1.53.0.snapshot 
![image](https://user-images.githubusercontent.com/70562142/101815778-b9fc9180-3b28-11eb-9cb3-80fb4b959f7b.png)
