### ISSUE TITLE
[SurvNet Interface] Important dates are set to one day prior after transfer

### ISSUE THREAD

**Issue by kwa20** [hzi-braunschweig/SORMAS-Project#3724]
### Bug Description
When case data is send to SurvNet, the report date, isolation period and symptom onset date are set to one day prior respectively than what is documented in SORMAS.
### Steps to Reproduce
1. Fill respective fields with data.
2. Send the case to the SurvNet instance.
3. Check relevant dates and compare with SORMAS entries.

### Expected Behavior
Dates appearing in SurvNet should conform to those entered in SORMAS.
### System Details
* Device:
* SORMAS version: 1.52.0
* Android version/Browser: Chrome
* Server URL: test1402.sormas-oegd.de
* User Role: admin, national user

**Comment by bernardsilenou** [comment]
The servers on both systems can be on different time zones, thus causing such a problem.
A possible solution i used when I encountered a similar problem was to transform the POSIX date time from sormas as a string, get the date component of the  string, convert it back to date when mapping.

**Comment by HolgerReiseVSys** [comment]
Has been fixed for the current version

**Comment by kwa20** [comment]
@HolgerReiseVSys I tried this on the test system where Netzlink updated the converter version to 1.0 but could not confirm the fix. The bug is still present.

**Comment by HolgerReiseVSys** [comment]
Seems like the SORMAS container runs in timezone Eurpe/Berlin and the converter runs in GMT.
The time zones need to match, so TZ=Eurpe/Berlin has to be set for the container of the converter, too.
