### ISSUE TITLE
Auto app update from  1.60.0, 1.61.2 to 1.63.0 failed

### ISSUE THREAD

**Issue by bernardsilenou** [hzi-braunschweig/SORMAS-Project#6529]
### Bug Description

Two tablets, one o, 160.0 and another on 161.2 were connected on the server: ease-international.sormas.netzlink.com/sormas-ui/. Serer was then upgraded to 1.63.0. When tablets were turned on, the was a prompt to upgrade. After choosing download, there was a second message that "app could not be downloaded, try again later.

### Steps to Reproduce

1. Set a server on 1.61.2, connect app to it and male sure all works fine
2. Upgrade server to 1.63.0
3. Connect mobile app to server and chose the option to updared the app
4. System could not auto update but ask you to try again latter
5. Click on try again later does not upgrade.

### Expected Behavior

App should update after user chose `Download` in the popup message "App update required"
### System Details

* Device: Android 7
* SORMAS version: 
* Android version/Browser:
* Server URL: release-international
* User Role: surveillance officer, contact officer

**Comment by MateStrysewske** [comment]
@bernardsilenou It's not an expected bug, users should generally be able to skip versions during the update. Your bug description however is missing the information what exactly happens. At which step does it fail?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
The massage was that the app could not update, "try later'

**Comment by MateStrysewske** [comment]
@bernardsilenou I'll try it out on my system

**Comment by MateStrysewske** [comment]
@bernardsilenou I tried to update from 1.61.2 to 1.63.0 and didn't receive an error, but instead some kind of an endless loop that is fixable. I suspect that's not the problem you were getting however.

**Comment by MateStrysewske** [comment]
For documentation purposes: the solution to the problem I was experiencing is to add `this.finishAffinity();` to the `onActivityResult` methods, inside the switch statement.

**Comment by bernardsilenou** [comment]
@MateStrysewske  this is the screenshot of the  samsung A9 tablet that is on 1.60 and working fine before server upgrade. No matter how many times you try, you keep getting the same message.

![Screenshot_20210831-193050_APMIS](https://user-images.githubusercontent.com/12996724/131550664-ec694a03-9695-4c34-9555-84f9a61d157a.jpg)

**Comment by MateStrysewske** [comment]
@bernardsilenou That's a download problem though, not an update problem. There's not really anything we can do here as far as I know, because we're simply using an internal Android functionality for the download, it's not a manual process that has been implemented by us.

Can you tell me which Android version the device is running on? I'll try to reproduce the problem on a virtual device with the same version.

**Comment by MateStrysewske** [comment]
@bernardsilenou That's a download problem though, not an update problem. There's not really anything we can do here as far as I know, because we're simply using an internal Android functionality for the download, it's not a manual process that has been implemented by us. The virtual tablet I've used when I tried to reproduce the problem was also running on Android 7, so it doesn't really seem to be a version-related issue...

**Comment by bernardsilenou** [comment]
@MateStrysewske  The tablet that I used is the latest Samsung tablet that we recommended to the users, it  on Android 11.
All other download features work well on the tablet. I can bring to you if the information on the image is not enough.
![model](https://user-images.githubusercontent.com/12996724/131693216-6523489e-4905-4a12-ab4c-745998c10516.png)

**Comment by MateStrysewske** [comment]
@bernardsilenou Since I don't have a device here where this is reproducable for me, having physical access to such a device so I can debug it would indeed help :)

**Comment by bernardsilenou** [comment]
@MateStrysewske  OK, I would make an appointment and bring to you.

**Comment by bernardsilenou** [comment]
@MateStrysewske  OK, I would make an appointment and bring to you.

**Comment by bernardsilenou** [comment]
@MateStrysewske   
I was so tight that I could not bring the tablet to you. I can bring it on Wednesday. 
However, I got the same report form Ivory coast, the test server (https://test-inhp-ci.sormas.netzlink.com/sormas-ui/#!about) was upgraded from 1.60.3 to 1.63.1 today and mobile devices can not upgrade.
@kwa20   @VitaliHZI  FYI

**Comment by MateStrysewske** [comment]
@bernardsilenou I can't reproduce the problem on an Android 11 tablet as well. I'll set up a tablet that is connected to the release-international server and check whether it's a server-specific problem once we have the next release.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- This video is what happended when i tried to connect a new installation of 1.63.1 to server (https://release-international.sormas.netzlink.com/sormas-ui/#!dashboard/surveillance) on the same version.
- Login was successful, app starts pulling infrastructure data and break after about 3 seconds.
- Device: A 7.0, Tecno P701, Build number: P701-PB04A-N-170523V26
https://user-images.githubusercontent.com/12996724/134531089-cc38d106-2bb0-49c8-baa0-905cef927543.MOV
@VitaliHZI, @BasilKaburi: you can add your findings here please.

**Comment by MateStrysewske** [comment]
@bernardsilenou Synchronization errors are not related to app update problems, please don't mix both of them up in one issue. ;) also, I can't provide any support concerning sync errors without logs.

I've just tried to update my Android 11 emulated device that was connected to release-international to 1.63.2 and it failed to download the app. I'm a bit lost here because it worked when I tried it out with a local server and an apk hosted on a server managed by our company. Starting to believe it's a configuration issue on the server because it doesn't seem to be caused by the download code in the mobile app itself.

**Comment by VitaliHZI** [comment]
@bernardsilenou and @MateStrysewske just an update here: 
I tested the upload/download and it still not working. 
I tested with an ASUS ZenPad Android 7.0. model number P00A
I had 1.63.1 on the tablet and after the auto update message is displayed, I get the same error like Bernard. 

How we could compare the server settings? 

BR 
Vitali

**Comment by MateStrysewske** [comment]
I don't know unfortunately, that's something that needs to be discussed with Netzlink.

**Comment by bernardsilenou** [comment]
I think @fhauptmann needs  to come in at this point.
@VitaliHZI I would suggest a meeting for you, Frank and me to have a look.

**Comment by bernardsilenou** [comment]
Here is the result after testing using Samsug Glaxy Tab A, with A11 on https://release-international.sormas.netzlink.com/sormas-ui/ on 1.63.2
- Auto download failed (this should have been corrected by @MateStrysewske last commit: https://github.com/hzi-braunschweig/SORMAS-Project/commit/6a07cd6a407de7f1c157a1e4840e29fc8e8883cf)
- After manual installation, all works fine with A11 (this was not the case for two different tablets with A7).
- @fhauptmann: The next step would be to get the logs when tablet on A7 sync with the server.

**Comment by MateStrysewske** [comment]
@bernardsilenou No, this wasn't fixed (as you can see in my comment above). I fixed another problem with the **installation** of the app, but the download problem persists because I have no idea why it happens. I didn't encounter these problems on an Android 11 device with my local server.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- We did a test with two tablets  samsung  A11 and tecno A7 on release-international, 
Serever detected that the version on tablet is 1.63.1, 1.63.2 could be downloaded as its on the server but download failed without any log from server side.
- We plan to upgrade the HZI test server to 1.63.2 and  the same test
@fhauptmann

**Comment by fhauptmann** [comment]
[sormas_app_upgrade_log.txt](https://github.com/hzi-braunschweig/SORMAS-Project/files/7266611/sormas_app_upgrade_log.txt)

Please find attached the corresponding server logs. But from my point of view the app logs should contain more relevant information.

**Comment by MateStrysewske** [comment]
@fhauptmann There is no error, that's the problem. For some reason, the download fails, but that's some internal Android mechanism that we can't control, and I haven't seen any useful logs that could tell us what the problem is.

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- You mentioned that on your local system, on A11, you could download 1.63.2, if the download is an android issue, then how comes you did not experience it?
-  We initially though it is a server issue and that is whey we are planning to test it  on the HZI server. Please can you advice if testing on the HZI server is needed?

**Comment by bernardsilenou** [comment]
@MateStrysewske 
- We did a test on the HZI server and got the same results. Thus this is likely not a server issue.
- Even with 1.64 release candite on https://release-international.sormas.netzlink.com/sormas-ui/, the download also failed with both A7 and A11.
- @fhauptmann and I suspect that there is something in the app that may be causing this issue. Can you connect a device to release-international and do a debug to find out from any logs that you can get from the tablet?
Here is the screenshot
![failedappdownload](https://user-images.githubusercontent.com/12996724/136055367-d683b83f-f3e5-42cb-a354-029b5164051a.png)

**Comment by MateStrysewske** [comment]
@bernardsilenou I have already tried that and received no meaningful log output, unfortunately. It's significantly harder on these test servers as well because they're running on a release version, so I can't properly debug them.

We're using an Android-internal logic to download the app that doesn't have anything to do with SORMAS. It's very well possible that the way we're using the mechanic doesn't reliably work anymore, but I have absolutely no idea what the reason might be.

**Comment by MateStrysewske** [comment]
@bernardsilenou After our meeting with Nigeria we know that this is also not a problem there, i.e. their mobile devices can properly download new .apk files. My guess is that this is in some way related to the servers managed by Netzlink, and there's nothing we can do about it. Please get in touch with Netzlink in order to find possible ways to fix this for the test instances.
