### ISSUE TITLE
[Cases] Error when contact supervisor unchecks the "place of stay differs from its responsible jurisdiction" checkbox

### ISSUE THREAD

**Issue by roxanamlendea** [hzi-braunschweig/SORMAS-Project#6595]
### Bug Description
When contact supervisor unchecks the "place of stay differs from its responsible jurisdiction" checkbox for a user that was created by a national user, he gets an error.

### Steps to Reproduce

1. Log in with NatUser and create a case (the place of stay must be different from the responsible jurisdiction)
2. Log in with contact supervisor (one that has jurisdiction over the case's place of stay or responsible jurisdiction) and open the case.
3. Uncheck the "place of stay differs from its responsible jurisdiction" checkbox.

### Actual Behavior
An error message appears.

### Screenshots
![error when contact supervisor unchecks the place of stay differs from its resposible jurisdiction box](https://user-images.githubusercontent.com/89522688/131854731-16bb12e3-1d5c-4b15-b524-485754213051.gif)

### System Details

* Device: Windows 10
* SORMAS version: 1.64.0-SNAPSHOT
* Android version/Browser: Chrome
* Server URL: test-de.sormas.netzlink.com
* User Role: NatUser

### Additional Information
This is also happening for:
- Case Officer
- Contact Officer
- Event Officer

**Comment by MateStrysewske** [comment]
The relatively simple solution here is that the contact supervisor should not be allowed to edit the value of the checkbox in the first place.

**Comment by syntakker** [comment]
Fixed by commit https://github.com/hzi-braunschweig/SORMAS-Project/commit/9b4f1760a21ee09b72d6a25e97d9df8ae07ad2a2 from #5969.
The error was caused by the missing `fetch = FetchType.LAZY` annotations in `Task.java`.

**Comment by roxanamlendea** [comment]
Unfortunately I could still reproduce it.
![error](https://user-images.githubusercontent.com/89522688/133383670-19ec028e-e05a-435f-b443-a0ebc6281b50.gif)

**Comment by roxanamlendea** [comment]
Also, this happens if the contact supervisor checks the "place of stay differs from its responsible jurisdiction" checkbox. Here. the case was created by the national user and the place of stay didn't differ from its responsible jurisdiction.
![check the juristiction box](https://user-images.githubusercontent.com/89522688/133384659-f580d45f-1848-4be9-b426-06e77d73d96f.gif)

**Comment by syntakker** [comment]
Right, the bug I thought was fixed only occured when saving (commit https://github.com/hzi-braunschweig/SORMAS-Project/commit/9b4f1760a21ee09b72d6a25e97d9df8ae07ad2a2 from #5969).

To reproduce the actual bug here, the user has to have no user right `CASE_TRANSFER`, in which case fields for region, district etc. are read only. The checkbox for "Place of stay of this case differs from its responsible jurisdiction" should then be read only, too, since an update of read only infrastructure fields is not possible.

**Comment by roxanamlendea** [comment]
Validated ticket on the latest version of Sormas 1.64.0-SNAPSHOT on environment test-de.sormas.netzlink.com
